name: Publish Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
      dryrun:
        description: 'DryRun'
        required: true
        type: boolean
        default: true

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure repository
      shell: bash
      run: |
        git config user.email "github-actions@hazelcast.com"
        git config user.name "GitHub Actions (Build Release)"

    - name: Validate the release
      uses: actions/github-script@v5
      with:
        script: |
          const scriptf = require('./.github/workflows/publish-release.js')
          const script = scriptf({github, context, core})
          await script.validateRelease()

    - name: Finalize GitHub release and milestone
      if: ${{ github.event.inputs.dryrun == 'false' }}
      uses: actions/github-script@v5
      with:
        script: |
          const scriptf = require('./.github/workflows/publish-release.js')
          const script = scriptf({github, context, core})
          await script.publishRelease()
          await script.closeMilestone()
