#
#
#

name: Callable (Organization)
on: 
  workflow_call:
    inputs:
      something:
        required: false
        type: boolean
        default: true
      ref:
        required: false
        type: string        
        default: ''

jobs:

  build-pr:
  
    name: "Callable (Organization)"
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Step Organization
        shell: bash
        run: |
          echo "Callable"
          if [ -z "${{ secrets.SOME_SECRET_TOKEN }}" ]; then
            echo "SECRET IS ABSENT"
          else
            echo "SECRET IS PRESENT"
          fi
          echo ${{ inputs.something }}
          echo "REF=${{ inputs.ref }}"
