#
# Workflow: Build PR
#

name: Build PR (Organization, Branch)
on: pull_request_target

jobs:

  build-pr:

    name: "Build PR (Organization, Branch) #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
    runs-on: ubuntu-latest

    steps:
    
      - name: Step
        shell: bash
        run: |
          echo "PR \#${{ github.event.pull_request.number }}"
          if [ -z "${{ secrets.SOME_SECRET_TOKEN }}" ]; then
            echo "SECRET IS ABSENT"
          else
            echo "SECRET IS PRESENT"
          fi

  build-pr-call:
  
    name: "Call (Organization, Branch)"        
    uses: ./.github/workflows/callme.yml
    secrets: inherit